n2n communication
IKNL/vantage6-node pull request #44
Opened 2021-11-17 13:51 UTC by bartvanb

First functional version where algorithms can connect to one another

2021-11-17 15:11 UTC, frankcorneliusmartin requested changes

2021-11-17 15:11 UTC, frankcorneliusmartin commented on dockerfiles/vpn-client/Dockerfile
> +ENTRYPOINT ["/app/entry.sh"]
This Dockerfile should be moved into the master repository.

2021-11-17 15:11 UTC, frankcorneliusmartin commented on dockerfiles/vpn-client/entry.sh
> +echo "Exiting, status $openvpn_child"
The we would have to move this file also

2021-11-17 15:11 UTC, frankcorneliusmartin commented on dockerfiles/vpn-configurator/Dockerfile
> +RUN apk add iproute2
Aaand this one

2021-11-17 15:11 UTC, frankcorneliusmartin commented on vantage6/node/__init__.py
> +            IsolatedNetworkManager(f"{self.ctx.docker_network_name}-net")
Why do we append the  `-net` or why is that not included in the `ctx.docker_network_name`?

2021-11-17 15:11 UTC, frankcorneliusmartin commented on vantage6/node/globals.py
> +NETWORK_CONFIG_IMAGE = 'harbor2.vantage6.ai/infrastructure/vpn-configurator'
Remark: 
These need to be overwritable from the configuration file. I created a separate issue for this: https://github.com/IKNL/vantage6-node/issues/45

Lets do that in a patch or minor version

2021-11-18 14:57 UTC, bartvanb commented on vantage6/node/__init__.py
> +            IsolatedNetworkManager(f"{self.ctx.docker_network_name}-net")
Good question. This is the only place in all repo's we use this property, so I added '-net' to this property in the Context class and removed the -net here.

2021-11-18 15:11 UTC, bartvanb commented on dockerfiles/vpn-client/Dockerfile
> +ENTRYPOINT ["/app/entry.sh"]
done

2021-11-18 15:11 UTC, bartvanb commented on dockerfiles/vpn-client/entry.sh
> +echo "Exiting, status $openvpn_child"
done

2021-11-18 15:11 UTC, bartvanb commented on dockerfiles/vpn-configurator/Dockerfile
> +RUN apk add iproute2
done

2021-11-18 15:34 UTC, frankcorneliusmartin approved these changes

2021-11-18 15:35 UTC, merged