Added check to see if docker is running when starting the node
IKNL/vantage6-node pull request #54
Opened 2021-12-13 15:42 UTC by bartvanb

Fix #7.

In this solution, the docker client tries to ping the docker server. The error is _intentionally_ caught as a general error as this may be OS-dependent. E.g. on windows, it throws a `pywintypes.error`, and we can only catch that specific error by importing pywintypes. Adding this to the dependencies will probably lead to more trouble than it's worth on Mac/Linux.

2021-12-13 15:44 UTC, bartvanb commented
Fix #8 as well!

2021-12-30 10:33 UTC, frankcorneliusmartin requested changes

2021-12-30 10:33 UTC, frankcorneliusmartin commented on vantage6/node/docker/utils.py
> +    except Exception as e:
I think catching `docker.errors.APIError` is more appropriate , see [here](https://docker-py.readthedocs.io/en/stable/client.html?highlight=ping#docker.client.DockerClient.ping)

2022-01-06 12:35 UTC, frankcorneliusmartin requested changes

2022-01-06 12:35 UTC, frankcorneliusmartin commented on vantage6/node/docker/utils.py
> +
Lets move this to the `vantage6.common` package and then replace the `check_if_docker_deamon_is_running` in both `vantage6.cli.node` and `vantage6.cli.server`

2022-01-25 15:20 UTC, frankcorneliusmartin approved these changes

2022-01-25 15:21 UTC, merged